@php($quantityStep = $product?->quantityStep() ?? '1')
@php($minimumOrderStep = $product?->usesWholeUnits() === false ? '0.01' : '1')
<div class="form-grid">
    <label class="field">KODE BARANG<input name="code" value="{{ old('code', $product?->code) }}" required maxlength="80">@error('code')<small class="field-error">{{ $message }}</small>@enderror</label>
    <label class="field">NAMA BARANG<input name="name" value="{{ old('name', $product?->name) }}" required maxlength="255">@error('name')<small class="field-error">{{ $message }}</small>@enderror</label>
    <label class="field">SATUAN<input name="unit" value="{{ old('unit', $product?->unit ?? 'pcs') }}" required maxlength="30" data-unit-input>@error('unit')<small class="field-error">{{ $message }}</small>@enderror</label>
    <label class="field">STOK MINIMUM<input type="number" min="0" step="{{ $quantityStep }}" name="minimum_stock" value="{{ old('minimum_stock', $product?->minimum_stock ?? 0) }}" required data-unit-quantity><small>Isi lebih dari 0 agar peringatan stok rendah dapat bekerja.</small>@error('minimum_stock')<small class="field-error">{{ $message }}</small>@enderror</label>
    <label class="field">SAFETY STOCK<input type="number" min="0" step="{{ $quantityStep }}" name="safety_stock" value="{{ old('safety_stock', $product?->safety_stock ?? 0) }}" required data-unit-quantity>@error('safety_stock')<small class="field-error">{{ $message }}</small>@enderror</label>
    <label class="field">TARGET STOK <small>(opsional)</small><input type="number" min="0" step="{{ $quantityStep }}" name="target_stock" value="{{ old('target_stock', $product?->target_stock) }}" placeholder="Target minimum perencanaan" data-unit-quantity>@error('target_stock')<small class="field-error">{{ $message }}</small>@enderror</label>
    <label class="field">MASA TINJAU (HARI)<input type="number" min="0" max="365" step="1" name="review_period_days" value="{{ old('review_period_days', $product?->review_period_days ?? 7) }}" required>@error('review_period_days')<small class="field-error">{{ $message }}</small>@enderror</label>
    <label class="field">MOQ / MIN. PESAN<input type="number" min="0" step="{{ $quantityStep }}" name="minimum_order_quantity" value="{{ old('minimum_order_quantity', $product?->minimum_order_quantity ?? 0) }}" required data-unit-quantity>@error('minimum_order_quantity')<small class="field-error">{{ $message }}</small>@enderror</label>
    <label class="field">KELIPATAN PESAN<input type="number" min="{{ $minimumOrderStep }}" step="{{ $quantityStep }}" name="order_multiple" value="{{ old('order_multiple', $product?->order_multiple ?? 1) }}" required data-unit-quantity data-unit-positive>@error('order_multiple')<small class="field-error">{{ $message }}</small>@enderror</label>
    <label class="field">KATEGORI<select name="category_id"><option value="">Tanpa kategori</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id', $product?->category_id) == $category->id)>{{ $category->name }}</option>@endforeach</select></label>
    <label class="field full">SUPPLIER<select name="supplier_id"><option value="">Tanpa supplier</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}" @selected(old('supplier_id', $product?->supplier_id) == $supplier->id)>{{ $supplier->name }} · lead time {{ $supplier->lead_time_days }} hari</option>@endforeach</select><small>Lead time supplier dipakai untuk menghitung target stok operasional.</small></label>
    <label class="checkbox field full"><input type="checkbox" name="active" value="1" @checked(old('active', $product?->active ?? true))> Barang aktif dan dapat digunakan pada data operasional berikutnya</label>
</div>
